import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-14">
          <h1>Logo</h1>
          <nav>
            <ul className="flex">
              <li className="mr-6">
                <a className="text-blue-500 hover:text-blue-800" href="/">
                  Home
                </a>
              </li>
              <li className="mr-6">
                <a
                  className="text-blue-500 hover:text-blue-800"
                  href="/customers"
                >
                  Customers
                </a>
              </li>
            </ul>
          </nav>
        </header>
        <main className="bg-white flex min-h-screen flex-col items-center justify-between pt-8 pb-8">
          {children}
        </main>
        <footer className="p-14">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
